progectS/Models/Plane.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace progectS.Models
{
    public class Plane
    {
        public Plane()
        {
            Days = new List<Day>();
            Date = DateTime.Now; 
        }
        [Key]
        public int ID { get; set; }

        [Display(Name = "שם התוכנית")]
        public string Name { get; set; }

        public User User { get; set; }


        public List<Day> Days { get; set; }

        [Display(Name = "תאריך תוכנית")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public SumALLProperties SumALLProperties
        {
            get
            {
                SumALLProperties Sum = new SumALLProperties(0, 0, 0);
                foreach (Day Day in Days)
                {
                    Sum.SumCaloris += Day.SumALLProperties.SumCaloris;
                    Sum.SumCarbohydrates += Day.SumALLProperties.SumCarbohydrates;
                    Sum.SumProteins += Day.SumALLProperties.SumProteins;
                }
                return Sum;
            }
        }

        public SumALLProperties SumALLPropertiesToDay
        {
            get
            {
                SumALLProperties Sum = new SumALLProperties(0, 0, 0);
                foreach (Day Day in Days)
                {
                    Sum.SumCaloris += Day.SumALLPropertiesToDay.SumCaloris;
                    Sum.SumCarbohydrates += Day.SumALLProperties.SumCarbohydrates;
                    Sum.SumProteins += Day.SumALLProperties.SumProteins;
                }
                return Sum;
            }
        }

        public void AddDays()
        {
            string[] Darry = new string[7];
            switch (Date.DayOfWeek)
            {
                case DayOfWeek.Sunday:
                    Darry[0] = "יום ראשון"; Darry[1] = "יום שני"; Darry[2] = "יום שלישי"; Darry[3] = "יום רביעי"; Darry[4] = "יום חמישי"; Darry[5] = "יום שישי"; Darry[6] = "שבת קודש";
                    break;
                case DayOfWeek.Monday:
                    Darry[6] = "יום ראשון"; Darry[0] = "יום שני"; Darry[1] = "יום שלישי"; Darry[2] = "יום רביעי"; Darry[3] = "יום חמישי"; Darry[4] = "יום שישי"; Darry[5] = "שבת קודש";
                    break;
                case DayOfWeek.Tuesday:
                    Darry[5] = "יום ראשון"; Darry[6] = "יום שני"; Darry[0] = "יום שלישי"; Darry[1] = "יום רביעי"; Darry[2] = "יום חמישי"; Darry[3] = "יום שישי"; Darry[4] = "שבת קודש";
                    break;
                case DayOfWeek.Wednesday:
                    Darry[4] = "יום ראשון"; Darry[5] = "יום שני"; Darry[6] = "יום שלישי"; Darry[0] = "יום רביעי"; Darry[1] = "יום חמישי"; Darry[2] = "יום שישי"; Darry[3] = "שבת קודש";
                    break;
                case DayOfWeek.Thursday:
                    Darry[3] = "יום ראשון"; Darry[4] = "יום שני"; Darry[5] = "יום שלישי"; Darry[6] = "יום רביעי"; Darry[0] = "יום חמישי"; Darry[1] = "יום שישי"; Darry[2] = "שבת קודש";
                    break;
                case DayOfWeek.Friday:
                    Darry[2] = "יום ראשון"; Darry[3] = "יום שני"; Darry[4] = "יום שלישי"; Darry[5] = "יום רביעי"; Darry[6] = "יום חמישי"; Darry[0] = "יום שישי"; Darry[1] = "שבת קודש";
                    break;
                case DayOfWeek.Saturday:
                    Darry[1] = "יום ראשון"; Darry[2] = "יום שני"; Darry[3] = "יום שלישי"; Darry[4] = "יום רביעי"; Darry[5] = "יום חמישי"; Darry[6] = "יום שישי"; Darry[0] = "שבת קודש";
                    break;
                default:
                    Darry[0] = "יום ראשון"; Darry[1] = "יום שני"; Darry[2] = "יום שלישי"; Darry[3] = "יום רביעי"; Darry[4] = "יום חמישי"; Darry[5] = "יום שישי"; Darry[6] = "שבת קודש";
                    break;
            }
            
            Days = new List<Day>();
            for (int i = 0; i < Darry.Length; i++)
            {
                Day day = new Day { DayName = Darry[i], Date = Date.AddDays(i), Plane = this };
                Days.Add(day);
            }

        }
    }

    
}

progectS/Controllers/ToDayController.cs
using Microsoft.AspNetCore.Mvc;
using progectS.Models;
using progectS.VModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data.Entity;

namespace progectS.Controllers
{
    public class ToDayController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddMealToDay(int? id)
        {
            if (DAL.Get.User.Mail == null) return RedirectToAction("Connect","user");
            VMAddTodayMeal VM = new VMAddTodayMeal
            {
                User = DAL.Get.User,
                UserID = DAL.Get.User.ID,
                TypeOfMeals = DAL.Get.TypeOfMeals.ToList(),
                MealToDAy = new MealToDAy(),
                Day = DAL.Get.Days.ToList().Find(D => D.ID == id),
                DayID = DAL.Get.Days.ToList().Find(D => D.ID == id).ID

            };
            return View(VM);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddMealToDay(VMAddTodayMeal VM)
        {
            if (DAL.Get.User.Mail == null) return RedirectToAction("Connect", "User");
            User user = DAL.Get.User;
            Day day = DAL.Get.Days.ToList().Find(d => d.ID == VM.DayID);
            TypeOfMeal type = DAL.Get.TypeOfMeals.ToList().Find(t => t.Id == VM.TypeId);
            MealToDAy meal = new MealToDAy
            {
                MealNameToDay = type,
                ToDay = day,
            };
            DAL.Get.Days.ToList().Find(d => d.ID == day.ID).AddMealToday(meal);
            DAL.Get.SaveChanges();

            return RedirectToAction("DaylDetails","plane", new { id = day.ID });
        }
        public IActionResult ToMealDetails(int? id)
        {

            MealToDAy meal = DAL.Get.MealsToDAy.Include(f => f.Foods).Include(m => m.MealNameToDay).ToList().Find(m => m.ID == id);
            VMToMealDetails VM = new VMToMealDetails
            {
                Food = DAL.Get.TodayFoodsInMeal.Include(f => f.Food).ToList().Find(f => f.MealToDAy.ID == meal.ID),
                Meal = DAL.Get.MealsToDAy.ToList().Find(m => m.ID == meal.ID),
                MealID = meal.ID

            };
            return View(VM);
        }
        public IActionResult AddFoodsInMealToDay(int? id)
        {
            if (id == null) return RedirectToAction(nameof(Index));
            MealToDAy meal = DAL.Get.MealsToDAy.ToList().Find(m => m.ID == id);
            VMToAddFoodInMeal VM = new VMToAddFoodInMeal
            {
                Meal = DAL.Get.MealsToDAy.ToList().Find(m => m.ID == id),
                MealID = DAL.Get.MealsToDAy.ToList().Find(m => m.ID == id).ID,

                FoodInMeal = new TodayFoodInMeal
                {
                    MealToDAy = meal
                }
            };
            return View(VM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddFoodsInMealToDay(VMToAddFoodInMeal VMfood)
        {
            MealToDAy meal = DAL.Get.MealsToDAy.ToList().Find(m => m.ID == VMfood.MealID);
            Food food = DAL.Get.Foods.ToList().Find(f => f.ID == VMfood.FoodID);
            DAL.Get.MealsToDAy.ToList().Find(m => m.ID == VMfood.MealID).AddFood(food, VMfood.FoodInMeal.Quantity,VMfood.FoodInMeal.Mood);
            DAL.Get.SaveChanges();
            return RedirectToAction(nameof(ToMealDetails), new { id = meal.ID });
        }

    }
}

progectS/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using progectS.Models;
using progectS.VModel;
using System.Data.Entity;

namespace progectS.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            List <Plane> plane = DAL.Get.Planes.ToList();
            return View(plane);
        }
        public IActionResult Connect()
        {
            User user = new User();
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Connect(User user)
        {
            User user1 = DAL.Get.Users.ToList().Find(u => u.Mail == user.Mail && u.Password == user.Password);
            if (user1 == null) return RedirectToAction(nameof(NoConnect));
            DAL.Get.User = user1;
            return RedirectToAction("ShowPlanes", "plane",new {id=DAL.Get.User.ID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registery(User user)
        {
            DAL.Get.Users.Add(user);
            DAL.Get.User = user;
            DAL.Get.SaveChanges();
            return RedirectToAction("ShowPlanes", "plane",new { id = DAL.Get.User.ID });
        }

        public IActionResult NoConnect()
        {
            User user = new User();
            return View(user);
        }

        public IActionResult UnConnect(int? id)
        {
            DAL.Get.User = new User { FirstName = "התחבר" };
            return RedirectToAction(nameof(Index), "home");
        }

        public IActionResult SohuUser(int? id)
        {
            VMAddIndices user = new VMAddIndices
            {
                User  = DAL.Get.User,
                Weight = DAL.Get.Indices.ToList().Find(w=> w.User.ID == DAL.Get.User.ID)
            };
            var Weights = new List<decimal>();
            var Days = new List<int>();

            foreach (Weight item in DAL.Get.User.Weight)
            {
                Weights.Add(item.MyWeight);
                Days.Add(item.Date.Day);
            }
            ViewBag.Weight = Weights.ToList();
            ViewBag.Days = Days.ToList();

            return View(user);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddIndices(VMAddIndices vmi)
        {
            if (DAL.Get.User.Mail == null) return RedirectToAction(nameof(Connect));
            User user = DAL.Get.User;
            DAL.Get.Users.ToList().Find(u=>u.ID == user.ID).AddWeight(vmi.Weight);
            DAL.Get.SaveChanges();
            return RedirectToAction(nameof(SohuUser), new { id = user.ID });
        }
        public IActionResult AddPlane()
        {
            Plane plane = new Plane();
            return View(plane);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPlane(Plane plane)
        {
            if (DAL.Get.User.Mail == null) return RedirectToAction(nameof(Connect));
            User user = DAL.Get.User;
            user.AddPlan(plane);
            DAL.Get.SaveChanges();
            return RedirectToAction("ShowPlanes", "plane", new { id = user.ID });
        }
        public IActionResult Deshbord(int? id)
        {
            if (DAL.Get.User.Mail == null) return RedirectToAction(nameof(Connect));
            VMDeshbord VM = new VMDeshbord
            {
                User= DAL.Get.User,
                Plane = DAL.Get.Planes.Include(d=> d.Days).ToList().Find(p=> p.ID == id),
                Meal = DAL.Get.Meals.Include(f=> f.Foods).ToList().Find(m=> m.Day.Plane.ID == id),
                MealToDAy = DAL.Get.MealsToDAy.Include(f => f.Foods).ToList().Find(m => m.ToDay.Plane.ID == id),
                Weight = DAL.Get.Indices.ToList().Find(w=> w.ID== id)


            };
            var caloris = new int[7];
            var Proteins = new int[7];
            var Carbohydrates = new int[7];
            var calorisToday = new int[7];
            var ProteinsToday = new int[7];
            var CarbohydratesToday = new int[7];
            var Days = new int[7];
            var Weights = new List<decimal>();
            var DaysL = new List<int>();
            Plane plane1 = DAL.Get.Planes.ToList().Find(p => p.ID == id);

            for (int i = 0; i < plane1.Days.Count; i++)
            {
                caloris[i] = plane1.Days[i].SumALLProperties.SumCaloris;
                Carbohydrates[i] = plane1.Days[i].SumALLPropertiesToDay.SumCarbohydrates;
                Proteins[i] = plane1.Days[i].SumALLProperties.SumProteins;
                calorisToday[i] = plane1.Days[i].SumALLPropertiesToDay.SumCaloris;
                ProteinsToday[i] = plane1.Days[i].SumALLPropertiesToDay.SumProteins;
                Carbohydrates[i] = plane1.Days[i].SumALLProperties.SumCarbohydrates;
            }
            int x = 0;
            foreach (Day item in plane1.Days)
            {
                Days[x] = item.Date.Day;
                x++;
            }
            foreach (Weight item in DAL.Get.User.Weight)
            {
                Weights.Add(item.MyWeight);
                DaysL.Add(item.Date.Day);
            }
            ViewBag.Carbohydrates = Carbohydrates;
            ViewBag.Proteins = Proteins;
            ViewBag.caloris = caloris;
            ViewBag.CarbohydratesToday = CarbohydratesToday;
            ViewBag.ProteinsToday = ProteinsToday;
            ViewBag.calorisToday = calorisToday;
            ViewBag.Days = Days;
            ViewBag.Weight = Weights.ToList();
            ViewBag.DaysL = DaysL.ToList();
            return View(VM); 

        }

    }
}

progectS/Views/plane/AddFoodsInMeal.cshtml
@model progectS.VModel.VMAddFoodInMeal

@{
    ViewData["Title"] = "הוספת מאכל לארוחה";
}

<h1>@Model.Meal.MealName.Name</h1>


<hr />
<div>
    <a asp-action="MealDetails" asp-route-id="@Model.MealID" class="btn btn-primary">בחזרה לארוחה</a>
</div>
<br />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddFoodsInMeal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="MealID" hidden="hidden" />

                <label asp-for="FoodID" class="control-label"></label>
                
                <select asp-for="FoodID" class="form-control" aria-label="בחר מאכל מתוך הרשימה">
                    @foreach (Food food in Model.FromApi)
                    {
                        <option class="" value="@food.ID">@food.Name</option>
                    }

                </select>
                <span asp-validation-for="FoodID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodInMeal.Quantity" class="control-label"></label>
                <input asp-for="FoodInMeal.Quantity" class="form-control" />
                <span asp-validation-for="FoodInMeal.Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="הוסף" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

progectS/Views/plane/AddMeal.cshtml
@model progectS.VModel.VMAddMealOfPlane

@{
    ViewData["Title"] = "הוספת ארוחה";
}

<h1>@Model.Day.DayName</h1>

<h4>הוספת ארוחה</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddMeal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="UserID" hidden="hidden" />
            <input asp-for="DayID" hidden="hidden" />
            
           
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" class="form-control">
                    @foreach (TypeOfMeal type in Model.TypeOfMeals)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <a asp-action="AddType">הוספת סוג ארוחה שאינו  מופיע ברשימה</a>


            <div class="form-group">
                <input type="submit" value="הוסף" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>|
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

progectS/Views/plane/AddType.cshtml
@model progectS.VModel.VMAddType

@{
    ViewData["Title"] = "הוספת סוג מאכל";
}


<h1>סוגי ארוחות</h1>
<hr />

<div class="row">
    @foreach (var item in Model.Types)
    {
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title">@Html.DisplayNameFor(model => model.Types.First().Name)</h5>
                    <p class="card-text"> @Html.DisplayFor(modelItem => item.Name)</p>
                    <a href="#" class="btn btn-primary">עוד על @item.Name</a>
                </div>
            </div>
        </div>
    }
</div>
<hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="AddType">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="@Model.Type.Name" class="control-label"></label>
                    <input asp-for="@Model.Type.Name" placeholder="הכנס סוג ארוחה" class="form-control" />
                    <span asp-validation-for="@Model.Type.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="צור" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="ShowPlanes" asp-route-id="@DAL.Get.User.ID">חזרה לתוכניות</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

progectS/Views/plane/DaylDetails.cshtml
@model progectS.VModel.VMDaylDetails

@{
    ViewData["Title"] = "DaylDetails";
}

<h1 class=" border-white">@Model.Day.Plane.Name</h1>

<div>
    <h4>@Model.Day.DayName</h4>
    <h4>@Model.Day.Date</h4>
    <hr />
</div>
<div class="row">
    <a asp-action="AddMeal" asp-route-id="@Model.Day.ID" class="btn btn-outline-secondary mx-3 ">הוספת ארוחה לתוכנית</a>
    <a asp-action="AddMealToDay" asp-controller="ToDay" asp-route-id="@Model.Day.ID" class="btn btn-outline-danger mx-3">הוספת ארוחה שאכלתי</a>
    <a asp-action="ShowPlanes" asp-route-id="@DAL.Get.User.ID" class="btn btn-outline-primary mx-3 ">הצגת תוכניות</a>
</div>
<hr />

@if (Model.Day.Meals.Count > 0)
{
<div class="aside " style=" width:100%;max-width:550px">
    <div class="card border border-danger">

        <div class="card-header">
            <h4 class="text-center">ארוחות שאכלתי היום</h4>
        </div>
        <div class="row text-center mx-auto">
            @foreach (MealToDAy item in Model.Day.MealsToDAy)
            {

                <div class="mx-auto my-2">
                    <div class="card border border-success" style="width:200px">

                        <div class="card-body text-center">

                            <h4 class="card-title">@item.MealNameToDay.Name</h4>
                            <p>סה"כ קלוריות: @item.SumCaloriesT</p>
                            <p>סה"כ חלבונים:  @item.SumCaloriesT</p>
                            <p>סה"כ פחמימות:  @item.SumCaloriesT</p>
                            <a asp-action="ToMealDetails" asp-controller="ToDay" asp-route-id="@item.ID" class="btn btn-outline-danger">הצג ארוחה</a>

                        </div>

                    </div>
                </div>
            }

        </div>
    </div>
</div>
        }
    

    @if (Model.Day.Meals.Count > 0)
    {

<div class="content ">
    <div class="card border border-success">
        <div class="card-header">
            <h4 class="text-center">ארוחות שאכלתי היום</h4>
        </div>
        <div class="row text-center mx-auto">
            @foreach (Meal item in Model.Day.Meals)
            {

                <div class="mx-auto my-2">
                    <div class="card border border-danger " style="width:200px">
                        <div class="card-body text-center">

                            <h4 class="card-title">@item.MealName.Name</h4>
                            <p>סה"כ קלוריות: @item.SumCalories</p>
                            <p>סה"כ חלבונים: @item.SumProteins</p>
                            <p>סה"כ פחמימות: @item.SumCarbohydrates</p>
                            <a asp-action="MealDetails" asp-route-id="@item.ID" class="btn btn-outline-success">הצג ארוחה</a>
                        </div>

                    </div>
                </div>
            }

        </div>
    </div>
</div>
    }

    <br />
    <br />

progectS/Views/plane/Delete.cshtml
@model progectS.Models.Plane

@{
    ViewData["Title"] = "Delete";
}

<h1>@Model.Name</h1>

<h3>האם הינך בטוח שברצונך למחוק את התוכנית?</h3>

<div>
    <hr />
    <form asp-action="Delete">
        <input type="submit" value="מחק" class="btn btn-danger" /> |
        <a asp-action="ShowPlanes" asp-route-id="@DAL.Get.User.ID" class="btn btn-primary">בחזרה לרשימת התוכניות</a>
    </form>
</div>

progectS/Views/plane/Details.cshtml
@model progectS.VModel.VMPlaneDetails
<div style="background-image:url(~/../../wwwroot/img/unnamed.png)">
    <div onload="load()">


        <h4>@Model.Plane.Name</h4>
        <hr />
        <a class="btn btn-outline-success" asp-action="Deshbord" asp-controller="user" asp-route-id="@Model.Plane.ID">מה המצב שלי</a>
        <dl class="row">

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Plane.Date)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Plane.Date)
            </dd>
        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Plane.ID }) |
        <a asp-action="ShowPlanes" asp-route-id="@Model.Plane.User.ID">בחזרה לתוכניות</a>
    </div>
    <div class="content">
        <div class="card">
            <div class="card-header">
                המצב בתוכנית
            </div>
            <div class="aside" style=" width:100%;max-width:500px">
                <canvas id="myChart" style="width:100%;max-width:450px"></canvas>
            </div>
        </div>
    </div>

    <div class="aside" style=" width:100%;max-width:550px">
        <div class="card">
            <div class="card-header">
                המצב בפועל
            </div>
            <div class="aside" style=" width:100%;max-width:500px">
                <canvas id="myChart1" style="width:100%;max-width:450px"></canvas>
            </div>
        </div>
    </div>

    <hr />
    @if (Model.Plane.Days.Count > 0)
    {
        <h4>  פירוט שבועי </h4>
        <table class="table table-success text-center">
            <thead>
                <tr class=" text-center">
                    <th class="text-center">תאריך</th>
                    <th class="text-center">יום</th>
                    <th class="text-center"></th>
                </tr>
            </thead>

            <tbody>

                @foreach (Day item in Model.Plane.Days)
                {

                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Date)</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DayName)
                        </td>
                        <td>
                            @Html.ActionLink("הצג ארוחות", "DaylDetails", new { id = item.ID })
                        </td>

                    </tr>
                }

            </tbody>
        </table>
    }
    <br />
    <br />
    <br />
</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>


    <script>

     var Proteins =@Html.Raw(Json.Serialize (ViewBag.Proteins));
     var caloris =@Html.Raw(Json.Serialize (ViewBag.caloris));
     var Carbohydrates =@Html.Raw(Json.Serialize (ViewBag.Carbohydrates));
     var ProteinsToday =@Html.Raw(Json.Serialize (ViewBag.ProteinsToday));
     var calorisToday =@Html.Raw(Json.Serialize (ViewBag.calorisToday));
     var CarbohydratesToday =@Html.Raw(Json.Serialize (ViewBag.CarbohydratesToday));
        var Days =@Html.Raw(Json.Serialize (ViewBag.Days));

        var xValues = Days;

             new Chart("myChart", {
        type: "line",
        data: {
             labels: xValues,
            datasets: [{
                data: Proteins,
                borderColor: "red",
                fill: false
            }, {
                data: caloris,
                borderColor: "green",
                fill: false
            }, {
                data: Carbohydrates,
                borderColor: "blue",
                fill: false
            }]
        },
        options: {
             legend: { display: false }
             }
             });
        var xValues = Days;

    new Chart("myChart1", {
        type: "line",
        data: {
            labels: xValues,
            datasets: [{
                data: ProteinsToday,
                borderColor: "red",
                fill: false
            }, {
                data: calorisToday,
                borderColor: "green",
                fill: false
            }, {
                data: CarbohydratesToday,
                borderColor: "blue",
                fill: false
            }]
        },
        options: {
            legend: { display: false }
        }
    });

    </script>

progectS/Views/plane/Edit.cshtml
@model progectS.Models.Plane

<h4>@Model.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

progectS/Views/plane/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div id="caart_container" style="width:400px;height:400px;border:1px solid #ddd;padding:1px;border-radius:4px">
    <canvas id="bar-chart"></canvas>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script>
    var Proteins =@Html.Raw(ViewBag.Proteins);
    var caloris =@Html.Raw(ViewBag.caloris);
    var Carbohydrates =@Html.Raw(ViewBag.Carbohydrates);
    var ctx = $("#bar-chart");
    var barChart = new Chart(ctx, {
        type: 'bar',
        date: {
            labels: caloris
            datasets[{
                label: "Proteins",
                data: Proteins,
                borderColor: 'red',
                fill: false
            },
            
            {
                label: "caloris",
                data: caloris,
                borderColor: 'green',
                fill: false
            },
            {
                label: "Carbohydrates",
                data: caloris,
                borderColor: 'blue',
                fill: false
            },] 
            
         },
        options: {
            legend: { display: false }
        }
       





    });

</script>